name: Deploy to SFDC #name of the workflow

#event -> on push to main branch, trigger the workflow

on: 
  push:
    branches: # what branch to trigger the workflow
      - main  # we want to trigger the workflow when we push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest # what environment to run the workflow on

    steps:
      - name: Checkout code # step name
        uses: actions/checkout@v3 # checkout the code from the repository

      - name: Set up Salesforce CLI # step name
        uses: amtrack/sfdx-action@v1.0.0 # use the Salesforce CLI action
        with:
          version: latest # use the latest version of Salesforce CLI

      - name: Authenticate to Salesforce # step name
        echo "${{ secrets.SFDX_AUTH_URL }}" > ./sfdx-auth-url.txt # write the sfdx auth URL to a file
        run: sfdx auth:sfdxurl:store -f sfdx-auth-url.txt -a fillics # authenticate to Salesforce using the sfdx auth URL
        
      - name: Deploy to Salesforce # step name
        run: sfdx force:source:deploy -p force-app -u fillics # deploy the source code to Salesforce
