name: Deploy to NewSFDC # name of the workflow

# event -> on push to preprod branch, trigger the workflow
on: 
  push:
    branches: # what branch to trigger the workflow
      - preprod  # we want to trigger the workflow when we push to preprod branch

jobs:
  deploy:
    runs-on: ubuntu-latest # what environment to run the workflow on

    steps:
      - name: Checkout code # step name
        uses: actions/checkout@v3 # checkout the code from the repository

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          sf --version # Verifies the installation successfully completed

      - name: Authenticate to Salesforce # step name
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" | sf org login sfdx-url --alias fillics --set-default --sfdx-url-stdin

      - name: Deploy to Salesforce # step name
        run: sf project deploy start force-app fillics --wait 30 # deploy the source code to Salesforce